package com.view.server;

public enum ChangedState {
	PLAYER_NAME_REQUEST,
	NEW_GAME_REQUEST,
	PLAYER_CHOICE_REQUEST,
	CARD_CHOICE_REQUEST,
	BLANK_CARD_CHOICE_REQUEST,
	REPARTITION_REQUEST,
	PLAYER_IDENTITY_REQUEST,
	ACTION_REQUEST,
	PLAYER_SWITCH_REQUEST,

	SHOW_GAME_WINNER,
	SHOW_ROUND_WINNER,
	SHOW_START_OF_ROUND,
	SHOW_PLAYER_IDENTITY,
	SHOW_REVEAL_ACTION,
	SHOW_ACCUSE_ACTION,
	SHOW_CARD_USE_ACTION,
	SHOW_CARD_LIST
}
